FROM node:21-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:21-alpine AS final
WORKDIR /app
COPY --from=builder ./app/dist ./dist
COPY package*.json .
COPY startup.sh .
RUN npm install --omit=dev

CMD [ "npm" "start" ]